version: '3'
services:
  nginx:
    container_name: freelance_nginx
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./docker-files/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/data/project
  app:
    container_name: freelance_app
    build:
      context: ./
    depends_on:
      - mysql
    volumes:
      - ./docker-files/nginx/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./docker-files/php-development.ini:/etc/php7/conf.d/php-development.ini
      - ./docker-files/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./:/data/project
  mysql:
    container_name: freelance_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "project"
      MYSQL_ROOT_PASSWORD: "password"
